In [2]:
# %pip install openmeteo-requests
# %pip install requests-cache retry-requests
# %pip install polars
# %pip install duckdb
# %pip install Numpy

In [3]:
import openmeteo_requests
import polars as pl
import requests_cache
from retry_requests import retry
from datetime import datetime, timedelta, timezone
import duckdb
import pyarrow

In [4]:
# api config
cache_session = requests_cache.CachedSession('.cache', expire_after = 3600)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

url = "https://api.open-meteo.com/v1/forecast"

Functionise the below to make easier

In [5]:
# Call config
# Oxford
_latitude = 52.52
_longitude = 13.41

# The order of variables in hourly or daily is important to assign them correctly below
# Would be better to define a dictionary of the variables then pass in the names/order to use in later arguments. Then there is no risk of assigning values of one and mislabelling them.
var_list = [
    "temperature_2m", 
    "relative_humidity_2m", 
    "apparent_temperature", 
    "precipitation_probability", 
    "precipitation", "rain", 
    "showers", "snowfall", 
    "snow_depth", 
    "weather_code", 
    "cloud_cover", 
    "wind_speed_10m"
]

params = {
	"latitude": _latitude,
	"longitude": _longitude,
	"hourly": var_list,
}

In [6]:
# api call
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
hourly = response.Hourly()

In [7]:
# Setting up the datetime length to create the dataframe with
start = datetime.fromtimestamp(hourly.Time(), timezone.utc)
end = datetime.fromtimestamp(hourly.TimeEnd(), timezone.utc)
freq = timedelta(seconds = hourly.Interval())

# Dataframe base
# get the columns before populating with metrics
df_base = pl.select(
    lat = response.Latitude(),
    long = response.Longitude(),
    extract_date = datetime.fromtimestamp(hourly.Time(), timezone.utc).date(),
    extract_time = datetime.now().time(),
    fc_datetime = pl.datetime_range(start, end, freq, closed="left")
).with_columns(
    fc_date = pl.col('fc_datetime').dt.date(),
    fc_hour = pl.col('fc_datetime').dt.strftime("%H")
)

col_exprs = {var: hourly.Variables(var_list.index(var)).ValuesAsNumpy() for var in var_list}

df_metrics = pl.DataFrame(
    col_exprs
)

df_raw = pl.concat([df_base, df_metrics], how='horizontal')

To do:
- Motherduck staging table
- Motherduck main table - recency rank
- Motherduck light table for latest values only (where recency rank = 1)

In [8]:
df_raw

shape: (168, 19)
┌───────┬───────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ lat   ┆ long      ┆ extract_da ┆ extract_ti ┆ … ┆ snow_depth ┆ weather_c ┆ cloud_cov ┆ wind_spee │
│ ---   ┆ ---       ┆ te         ┆ me         ┆   ┆ ---        ┆ ode       ┆ er        ┆ d_10m     │
│ f64   ┆ f64       ┆ ---        ┆ ---        ┆   ┆ f32        ┆ ---       ┆ ---       ┆ ---       │
│       ┆           ┆ date       ┆ time       ┆   ┆            ┆ f32       ┆ f32       ┆ f32       │
╞═══════╪═══════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 3.0       ┆ 100.0     ┆ 9.511088  │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 3.0       ┆ 95.0      ┆ 6.618519  │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 3.0       ┆ 100.0     ┆ 7.928177  │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 3.0       ┆ 100.0     ┆ 8.209263  │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 3.0       ┆ 100.0     ┆ 8.287822  │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
│ …     ┆ …         ┆ …          ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 1.0       ┆ 30.0      ┆ 6.48      │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 1.0       ┆ 33.0      ┆ 5.804825  │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 1.0       ┆ 35.0      ┆ 5.506941  │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 2.0       ┆ 46.0      ┆ 5.447788  │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
│ 52.52 ┆ 13.419998 ┆ 2026-03-21 ┆ 21:51:07.4 ┆ … ┆ 0.0        ┆ 2.0       ┆ 56.0      ┆ 5.4       │
│       ┆           ┆            ┆ 12808      ┆   ┆            ┆           ┆           ┆           │
└───────┴───────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
# Initialise the duckdb database
db_token =

In [10]:
con = duckdb.connect(f'md:?"motherduck_token={db_token}')

In [11]:
con.sql("SHOW DATABASES").show()

┌───────────────────────┐
│     database_name     │
│        varchar        │
├───────────────────────┤
│ WeatherData           │
│ md_information_schema │
│ my_db                 │
│ sample_data           │
└───────────────────────┘

In [12]:
df= con.sql("SELECT * FROM sample_data.nyc.rideshare LIMIT 10").pl()

In [13]:
df.head()

shape: (5, 24)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ hvfhs_lic ┆ dispatchi ┆ originati ┆ request_d ┆ … ┆ shared_ma ┆ access_a_ ┆ wav_reque ┆ wav_matc │
│ ense_num  ┆ ng_base_n ┆ ng_base_n ┆ atetime   ┆   ┆ tch_flag  ┆ ride_flag ┆ st_flag   ┆ h_flag   │
│ ---       ┆ um        ┆ um        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
│           ┆ str       ┆ str       ┆ μs]       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ HV0003    ┆ B03404    ┆ B03404    ┆ 2022-11-0 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:04:09  ┆   ┆           ┆           ┆           ┆          │
│ HV0003    ┆ B03404    ┆ B03404    ┆ 2022-11-0 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:42:26  ┆   ┆           ┆           ┆           ┆          │
│ HV0003    ┆ B03404    ┆ B03404    ┆ 2022-11-0 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:11:53  ┆   ┆           ┆           ┆           ┆          │
│ HV0003    ┆ B03404    ┆ B03404    ┆ 2022-11-0 ┆ … ┆ N         ┆           ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 00:45:30  ┆   ┆           ┆           ┆           ┆          │
│ HV0005    ┆ B03406    ┆ null      ┆ 2022-10-3 ┆ … ┆ N         ┆ N         ┆ N         ┆ N        │
│           ┆           ┆           ┆ 1         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 23:56:33  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
df_raw = df_raw.to_arrow()

In [15]:
con.sql('CREATE TABLE my_db.raw_test AS SELECT * FROM df_raw')

In [ ]:
# send the df_raw into the staging table - label it as such